spring.application.name=demo
spring.security.user.name=vishnu
spring.security.user.password=1234

spring.datasource.url=jdbc:mysql://localhost:3306/securitydb
spring.datasource.username=root
spring.datasource.password=Vishnu1234&&

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
